[package]
name = "listenfd"
version = "0.1.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "A simple library to work with listenfds passed from the outside (systemd/catflap socket activation)"
keywords = ["socket", "listenfd", "systemd", "socketactivation"]
homepage = "https://github.com/mitsuhiko/rust-listenfd"
readme = "README.md"
license = "MIT/Apache-2.0"

[target."cfg(not(windows))".dependencies]
libc = "0.2.40"
